eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
server:
  port: 8111
spring:
  application:
    name: service-zuul
zuul:
  routes:
    fredapi:
      path: /fredapi/**
      serviceId: service-fred
    ribbonapi:
      path: /ribbonapi/**
      serviceId: service-ribbon
