server:
  port: 8012
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer1:8011/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: eureka-server