server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: eureka-server
