server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: eureka-server
logging:
  file: eureka-server-peer2.log