server:
  port: 8011
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer2:8012/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: eureka-server